#!/usr/bin/perl
# Build the byte-offset prefix index for ring-dictionary-v2 from the main dictionary.
#
# Output:
#   utils/prefix-index.js  (ES module exporting a complete 1-letter + 2-letter
#     byte-offset table into the UTF-16LE dict, so English lookup() never scans
#     from offset 0.)
#
# The Chinese inverted index (assets/common/dic/cn-inv.bin) is now built by
# tools/build-cn-inv.mjs  (run:  node tools/build-cn-inv.mjs). It replaced the
# old cn-index.txt: it maps each CJK char to byte offsets into the main dict,
# so Chinese search seeks directly to candidate entries instead of scanning the
# whole file, and it avoids duplicating definition text.
#
# Re-run after updating txtTrans_1.0.txt:
#   perl tools/build-index.pl
#   node tools/build-cn-inv.mjs

use strict;
use warnings;
use utf8;
use open IO => ':raw';

my $DICT = 'assets/common/dic/txtTrans_1.0.txt';
my $PX_OUT = 'utils/prefix-index.js';

# --- read raw bytes ---
open(my $fh, '<:raw', $DICT) or die "cannot open $DICT: $!";
local $/;
my $raw = <$fh>;
close($fh);

# decode UTF-16LE (no BOM in this file) into a perl character string
my $decoded = '';
my $len = length($raw);
for (my $i = 0; $i + 1 < $len; $i += 2) {
    my $lo = ord(substr($raw, $i, 1));
    my $hi = ord(substr($raw, $i + 1, 1));
    my $cp = $lo | ($hi << 8);
    $decoded .= chr($cp);
}
my $tlen = length($decoded);
my $dictBytes = length($raw);
my $az = qr/^[a-z]$/;

# --- walk entries (word line, then definition line) and record prefix offsets ---
my %one;      # single-letter -> byte offset
my $two;      # two-letter    -> byte offset
my %two;
my $charPos = 0;

while ($charPos + 1 < $tlen) {
    my $nl = index($decoded, "\n", $charPos);
    last if $nl == -1;
    my $word = substr($decoded, $charPos, $nl - $charPos);
    my $wlen = length($word);
    # record prefix offsets (byte offset into UTF-16LE = charPos * 2)
    if ($wlen >= 1) {
        my $c1 = substr($word, 0, 1);
        $one{$c1} = $charPos * 2 if ($c1 =~ $az && !exists $one{$c1});
    }
    if ($wlen >= 2) {
        my $c2 = substr($word, 0, 2);
        $two{$c2} = $charPos * 2 if ($c2 =~ /^[a-z][a-z]$/ && !exists $two{$c2});
    }
    # skip the definition line
    $charPos = $nl + 1;
    my $nl2 = index($decoded, "\n", $charPos);
    last if $nl2 == -1;
    $charPos = $nl2 + 1;
}

# --- emit prefix-index.js ---
open(my $px, '>:encoding(UTF-8)', $PX_OUT) or die "cannot write $PX_OUT: $!";
print $px "// AUTO-GENERATED by tools/build-index.pl — do not edit by hand.\n";
print $px "// Byte offsets into assets/common/dic/txtTrans_1.0.txt (UTF-16LE, 2 bytes/char).\n";
print $px "export default {\n";
my @oneKeys = sort keys %one;
for (my $i = 0; $i < @oneKeys; $i++) {
    my $k = $oneKeys[$i];
    print $px "  $k:" . $one{$k} . ($i == $#oneKeys && !%two ? '' : ',') . "\n";
}
my @twoKeys = sort keys %two;
for (my $i = 0; $i < @twoKeys; $i++) {
    my $k = $twoKeys[$i];
    print $px "  $k:" . $two{$k} . ($i == $#twoKeys ? '' : ',') . "\n";
}
print $px "}\n";
print $px "// Total byte length of the UTF-16LE main dict (used by randomWord seek).\n";
print $px "export const DICT_SIZE = $dictBytes\n";
close($px);

print "1-letter prefixes: " . scalar(keys %one) . ", 2-letter prefixes: " . scalar(keys %two) . "\n";
print "wrote $PX_OUT\n";
